version: '3'

services: 
  streamingnetflixpg:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'streamingnetflix'
    restart: always
    volumes: 
      - streamingnetflix-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes: 
  streamingnetflix-data: